name: Pull request

on:
  pull-request:
    branches:
      - main

jobs:

  affected:
    name: Detect affected projects
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    outputs:
      NX_BASE: ${{ steps.setSHAs.outputs.base }}
      NX_HEAD: ${{ steps.setSHAs.outputs.head }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        id: setSHAs
        with:
          main-branch-name: main
          workflow-id: pull-request.yml
      - name: Install dependencies
        run: npm ci
      - name: Shows affected projects
        shell: bash
        run: npx nx print-affected