name: Push to master

on:
  push:
    branches:
      - master

jobs:

  affected:
    name: Detect affected projects
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    outputs:
      NX_BASE: ${{ steps.setSHAs.outputs.base }}
      NX_HEAD: ${{ steps.setSHAs.outputs.head }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        id: setSHAs
        with:
          main-branch-name: main
          workflow-id: push.yml
      - name: Install dependencies
        run: npm ci
      - name: Shows affected projects
        shell: bash
        run: npx nx print-affected

  version:
    name: Version projects
    runs-on: ubuntu-latest
    needs: [affected]
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Install dependencies
        run: npm ci
      # Do not run in parallel because it keeps track of last commit while tagging
      - name: Version affected projects
        shell: bash
        run: npx nx affected --target=version --push --baseBranch=main --base=${{ needs.affected.outputs.NX_BASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}